### ISSUE TITLE
can I ask some question?

### ISSUE THREAD

**Issue by modernmanxxx** [PacktPublishing/Python-3-Object-Oriented-Programming-Third-Edition#1]

**Comment by modernmanxxx** [comment]
where can I get the module which name is "path"(in chapter13→Multiprocessing→Queues→searching_with_queues.py).
Neither the win platform nor the Linux platform I can install "path" from pip.

**Comment by modernmanxxx** [comment]
hello,where can I get the module which name is "path"(in chapter13→Multiprocessing→Queues→searching_with_queues.py).
Neither the windows platform nor the Linux platform I can install "path" from pip.

**Comment by thisshri** [comment]
@modernmanxxx  I am not sure but I think this should work for you, `from os import path`.

**Comment by modernmanxxx** [comment]
I've tried using "from OS import path" and "from pathlib import path" and it doesn't work properly
pathlib.Path():AttributeError
'WindowsPath' object has no attribute 'listdir'

os.path: TypeError
'module' object is not callable

**Comment by thisshri** [comment]
try exactly `from os import path`
Its `os` not `OS`
> And path is not callable, means its a module, you can't call it like a function.
run `dir(path)` to see what are the properties and functions available in the path module.

**Comment by modernmanxxx** [comment]
I'm not going to dwell on this anymore. Thank you for your help.

**Comment by thisshri** [comment]
Read this, http://thomas-cokelaer.info/tutorials/python/module_os.html
