### ISSUE TITLE
AttributeError: 'SecretString' object has no attribute

### ISSUE THREAD

**Issue by felsen** [PacktPublishing/Python-3-Object-Oriented-Programming-Third-Edition#4]
@dusty-phillips

`__plain_text` variable is not part of the `SecretString` class, instead of calling `__plain_string` i think called `__plain_text `if i am not wrong,

![image](https://user-images.githubusercontent.com/7158481/108183596-3e265300-7130-11eb-8060-28c1b448c8c2.png)

**Comment by dusty-phillips** [comment]
Yes, that is correct. It's a funny edge case where I updated the example, and the demo was still functioning correctly for the wrong reasons.
